import './css/global.css'

export const metadata = {
  title: 'Portfolio - Mentorias',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
      <body className='flex'>{children}</body>
    </html>
  )
}
